# Generated by Django 4.0.4 on 2022-05-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo_casa', models.CharField(max_length=50, verbose_name='Modelo De Casa')),
                ('poligono_casa', models.CharField(max_length=50, verbose_name='Poligono De Casa')),
                ('numero_casa', models.IntegerField(max_length=50, verbose_name='Numero De Casa')),
                ('obra_casa', models.CharField(max_length=50, verbose_name='Codigo De Obra')),
                ('agrupacion_casa', models.CharField(max_length=100, verbose_name='Agrupacion')),
                ('porcentaje_casa', models.IntegerField(max_length=50, verbose_name='Porcentaje %')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado El ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado El ')),
            ],
            options={
                'verbose_name': 'Casa',
                'verbose_name_plural': 'Casas',
            },
        ),
    ]
