# Generated by Django 4.0.4 on 2022-05-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='numero_casa',
            field=models.IntegerField(verbose_name='Numero De Casa'),
        ),
        migrations.AlterField(
            model_name='page',
            name='porcentaje_casa',
            field=models.IntegerField(verbose_name='Porcentaje %'),
        ),
    ]
