# Generated by Django 4.0.4 on 2022-05-20 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_page_content_alter_page_porcentaje_casa'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='contratista_casa',
            field=models.CharField(default=1, max_length=50, verbose_name='Contratista De La Casa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='estado_contratista',
            field=models.BooleanField(default=1, verbose_name='¿Activo?'),
            preserve_default=False,
        ),
    ]
