# Generated by Django 4.0.4 on 2022-05-22 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_page_contratista_casa_page_estado_contratista'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='progreso_casa',
            field=models.IntegerField(default=1, verbose_name='Progreso De La Casa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='estado_contratista',
            field=models.BooleanField(verbose_name='Estado Del Contratista'),
        ),
    ]
