# Generated by Django 4.0.4 on 2022-05-23 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_page_progreso_casa_alter_page_estado_contratista'),
    ]

    operations = [
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo_casa', models.CharField(max_length=50, unique=True, verbose_name='Modelo De Casa')),
                ('precio_agru24', models.IntegerField(verbose_name='Precio De La Agrupacion 24')),
                ('precio_agru25', models.IntegerField(verbose_name='Precio De La Agrupacion 25')),
                ('precio_agru26', models.IntegerField(verbose_name='Precio De La Agrupacion 26')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado El ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado El ')),
            ],
            options={
                'verbose_name': 'Precio Agrupacion',
                'verbose_name_plural': 'Precios Agrupaciones',
            },
        ),
    ]
