# Generated by Django 4.0.4 on 2022-05-23 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precio',
            name='precio_agru24',
            field=models.FloatField(verbose_name='Precio De La Agrupacion 24'),
        ),
        migrations.AlterField(
            model_name='precio',
            name='precio_agru25',
            field=models.FloatField(verbose_name='Precio De La Agrupacion 25'),
        ),
        migrations.AlterField(
            model_name='precio',
            name='precio_agru26',
            field=models.FloatField(verbose_name='Precio De La Agrupacion 26'),
        ),
    ]
