# Generated by Django 4.0.4 on 2022-05-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_precio_options_page_precio_agru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='precio_agru',
            field=models.FloatField(verbose_name='Precio De La Agrupacion'),
        ),
    ]
