# Generated by Django 4.0.4 on 2022-05-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_page_precio_agru'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contratista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_persona', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('dui_persona', models.CharField(max_length=50, unique=True, verbose_name='Dui')),
                ('nit_persona', models.CharField(max_length=50, unique=True, verbose_name='Nit')),
                ('estado_contratista', models.BooleanField(verbose_name='Estado Del Contratista')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado El ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado El ')),
            ],
            options={
                'verbose_name': 'Contratista',
                'verbose_name_plural': 'Contratistas',
            },
        ),
    ]
