# Generated by Django 4.0.4 on 2022-05-24 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_contratista'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(max_length=50, unique=True, verbose_name='Nombre Del Proyecto')),
                ('lugar_proyecto', models.CharField(max_length=50, unique=True, verbose_name='Lugar Del Proyecto')),
                ('estado_proyecto', models.BooleanField(verbose_name='Estado Del Proyecto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado El ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado El ')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
            },
        ),
    ]
