# Generated by Django 4.0.4 on 2022-05-24 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_proyectos'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='proyecto_casa',
            field=models.CharField(default=1, max_length=50, verbose_name='Proyecto Al Que Pertenece'),
            preserve_default=False,
        ),
    ]
