# Generated by Django 4.0.4 on 2022-05-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_page_proyecto_casa'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='fecha_generica',
            field=models.CharField(default=1, max_length=50, verbose_name='Fecha Generica'),
            preserve_default=False,
        ),
    ]
