# Generated by Django 4.0.4 on 2022-05-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_inmobiliaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='creado_user',
            field=models.CharField(default=1, max_length=50, verbose_name='Creado Por '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='update_user',
            field=models.CharField(default=1, max_length=50, verbose_name='Actualizado Por'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha De Creacion El'),
        ),
        migrations.AlterField(
            model_name='page',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha De Actualizacion'),
        ),
    ]
