# Generated by Django 4.0.4 on 2022-06-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_page_creado_user_page_update_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_anuncio', models.CharField(max_length=50, unique=True, verbose_name='Nombre De Quien Anuncia')),
                ('title_anuncio', models.CharField(max_length=50, unique=True, verbose_name='Titulo Del Anuncio')),
                ('content_anuncio', models.TextField(blank=True, verbose_name='Mensaje')),
                ('state_anuncio', models.BooleanField(verbose_name='¿Visible?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado El ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado El ')),
            ],
            options={
                'verbose_name': 'Anuncio',
                'verbose_name_plural': 'Anuncios',
            },
        ),
        migrations.AlterField(
            model_name='page',
            name='precio_agru',
            field=models.FloatField(verbose_name='Precio De La Agrupacion $ '),
        ),
    ]
