# Generated by Django 4.0.4 on 2022-06-03 12:50

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_anuncio_alter_page_precio_agru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='content_anuncio',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Mensaje'),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='name_anuncio',
            field=models.CharField(max_length=50, verbose_name='Nombre De Quien Anuncia'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Comentarios'),
        ),
    ]
